-- AlterTable
ALTER TABLE `Tarea` ADD COLUMN `dueDate` DATETIME(3) NULL;
ALTER TABLE `Tarea` ADD COLUMN `sessions` INTEGER NOT NULL DEFAULT 1;
ALTER TABLE `Tarea` ADD COLUMN `sortOrder` INTEGER NOT NULL DEFAULT 0;
